/*!
 * JEC JDI Node Module
 * Copyright(c) 2017 Pascal ECHEMANN
 * Apache 2.0 Licensed
 * This is a part of the JEC Projects: <https://github.com/pechemann/JEC>
 */

declare module "jec-jdi" {

export interface InjectableParams {    type?: Symbol;    retention?: Array<string>;    qualifier?: string;    scope?: string;}export interface InjectParams {    type?: Symbol;    retention?: Array<string>;    qualifier?: string;}export function Inject(params?: InjectParams): Function;export function Injectable(params?: InjectableParams): Function;export abstract class AbstractScope implements Scope {    constructor(type: string);    private _type;    getType(): string;}export class ApplicationScoped extends AbstractScope implements Scope {    constructor();}export class RequestScoped extends AbstractScope implements Scope {    constructor();}export interface Scope {    getType(): string;}export enum ScopeType {    DEPENDENT = "dependent",    APPLICATION = "application",    SESSION = "session",    REQUEST = "request",}export class SessionScoped extends AbstractScope implements Scope {    constructor();}export class JdiError extends Error {    constructor(message: string);}export interface Bean {    getScope(): Scope;}export interface BeanManager {}export interface InjectionPoint {    getBean(): Bean;    getType(): any;    getMember(): any;}export interface JDI {    getContainer(): JdiContainer;    getBeanManager(): BeanManager;}export interface JdiContainer {}export interface JdiContext {    getScope(): Scope;    isActive(): boolean;}export enum JdiConnectorRefs {    INJECT_PARAMETER_CONNECTOR_REF = "com.jec.commons.jdi.annotations.Inject#parameter",    INJECT_PROPERTY_CONNECTOR_REF = "com.jec.commons.jdi.annotations.Inject#property",    INJECTABLE_CONNECTOR_REF = "com.jec.commons.jdi.annotations.Injectable",}}